
package org.urbaniak.studia.sem2.integracja.service;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "MusicWebServiceImplService", targetNamespace = "http://service.integracja.sem2.studia.urbaniak.org/", wsdlLocation = "http://localhost:8888/music.ws?wsdl")
public class MusicWebServiceImplService
    extends Service
{

    private final static URL MUSICWEBSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(org.urbaniak.studia.sem2.integracja.service.MusicWebServiceImplService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = org.urbaniak.studia.sem2.integracja.service.MusicWebServiceImplService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8888/music.ws?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8888/music.ws?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        MUSICWEBSERVICEIMPLSERVICE_WSDL_LOCATION = url;
    }

    public MusicWebServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MusicWebServiceImplService() {
        super(MUSICWEBSERVICEIMPLSERVICE_WSDL_LOCATION, new QName("http://service.integracja.sem2.studia.urbaniak.org/", "MusicWebServiceImplService"));
    }

    /**
     * 
     * @return
     *     returns MusicWebServiceImpl
     */
    @WebEndpoint(name = "MusicWebServiceImplPort")
    public MusicWebServiceImpl getMusicWebServiceImplPort() {
        return super.getPort(new QName("http://service.integracja.sem2.studia.urbaniak.org/", "MusicWebServiceImplPort"), MusicWebServiceImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MusicWebServiceImpl
     */
    @WebEndpoint(name = "MusicWebServiceImplPort")
    public MusicWebServiceImpl getMusicWebServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.integracja.sem2.studia.urbaniak.org/", "MusicWebServiceImplPort"), MusicWebServiceImpl.class, features);
    }

}
