
package org.urbaniak.studia.sem2.integracja.service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "MusicWebServiceImpl", targetNamespace = "http://service.integracja.sem2.studia.urbaniak.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MusicWebServiceImpl {


    /**
     * 
     * @param arg0
     * @return
     *     returns org.urbaniak.studia.sem2.integracja.service.Artist
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "add", targetNamespace = "http://service.integracja.sem2.studia.urbaniak.org/", className = "org.urbaniak.studia.sem2.integracja.service.Add")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://service.integracja.sem2.studia.urbaniak.org/", className = "org.urbaniak.studia.sem2.integracja.service.AddResponse")
    public Artist add(
        @WebParam(name = "arg0", targetNamespace = "")
        Artist arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "remove", targetNamespace = "http://service.integracja.sem2.studia.urbaniak.org/", className = "org.urbaniak.studia.sem2.integracja.service.Remove")
    @ResponseWrapper(localName = "removeResponse", targetNamespace = "http://service.integracja.sem2.studia.urbaniak.org/", className = "org.urbaniak.studia.sem2.integracja.service.RemoveResponse")
    public void remove(
        @WebParam(name = "arg0", targetNamespace = "")
        Artist arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns org.urbaniak.studia.sem2.integracja.service.Artist
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "update", targetNamespace = "http://service.integracja.sem2.studia.urbaniak.org/", className = "org.urbaniak.studia.sem2.integracja.service.Update")
    @ResponseWrapper(localName = "updateResponse", targetNamespace = "http://service.integracja.sem2.studia.urbaniak.org/", className = "org.urbaniak.studia.sem2.integracja.service.UpdateResponse")
    public Artist update(
        @WebParam(name = "arg0", targetNamespace = "")
        Artist arg0);

    /**
     * 
     * @return
     *     returns java.util.List<org.urbaniak.studia.sem2.integracja.service.Artist>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "fetch", targetNamespace = "http://service.integracja.sem2.studia.urbaniak.org/", className = "org.urbaniak.studia.sem2.integracja.service.Fetch")
    @ResponseWrapper(localName = "fetchResponse", targetNamespace = "http://service.integracja.sem2.studia.urbaniak.org/", className = "org.urbaniak.studia.sem2.integracja.service.FetchResponse")
    public List<Artist> fetch();

}
