## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('wifi-project')
    obj.source = ['wifi-project.cc',
                  'wifi-trace-apps.cc',
                  'packet-listener.cc']
